config/routes.rb
Redbrew::Application.routes.draw do
  resources :users

  resources :plugins
  root :to => 'plugins#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/plugin.rb
class Plugin < ActiveRecord::Base
  attr_accessible :id, :name, :url, :description, :formula, :create_user_id, :update_user_id, :deleted_at, :plugins, :downloads

  validates :name, :uniqueness => true, :presence => true

  belongs_to :create_user, :class_name => 'User', :foreign_key => 'create_user_id'
  belongs_to :update_user, :class_name => 'User', :foreign_key => 'update_user_id'

  acts_as_paranoid

  def self.find(*args)
    if args.first && args.first.is_a?(String) && !args.first.match(/^\d*$/)
      project = find_by_name(*args)
      raise ActiveRecord::RecordNotFound, "Couldn't find Project with identifier=#{args.first}" if project.nil?
      project
    else
      super
    end
  end

  def self.search_by_keywords(keywords)
    plugins = Arel::Table.new :plugins
    conds = keywords.strip.split.map do |key|
      [:url, :description, :formula].inject (plugins[:name].matches("%#{key}%")) do |condition, col|
        condition.or(plugins[col].matches("%#{key}%"))
      end
    end

    conds.inject (Plugin) {|query, cond| query.where(cond) }
  end
end

app/models/setting.rb
class Setting
  begin
    @@available_settings = YAML.load(File.open("#{Rails.root}/config/settings.yml"))
  rescue
    @@available_settings = {}
  end

  def self.[](key)
    @@available_settings[key.to_s] || ENV[key.to_s]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :id, :name, :github_name, :icon_url

  has_many :create_plugins, :class_name => 'Plugin', :foreign_key => 'create_user_id'
  has_many :update_plugins, :class_name => 'Plugin', :foreign_key => 'update_user_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include ApplicationHelper
end

app/controllers/login_controller.rb
require 'oauth2'
require 'json'
class LoginController < ApplicationController
  protect_from_forgery :only => ["logout"]

  def index
  end

  def oauth
    session[:oauth_referer] = request.referer
    callback_url = url_for(:controller => 'login', :action => 'oauth_callback')
    redirect_to client.auth_code.authorize_url(:redirect_uri => callback_url)
  end

  def oauth_callback
    code = params[:code]
    begin
      token = client.auth_code.get_token(code, :redirect_uri => session[:oauth_referer])
    rescue => e
      raise e
      flash[:notice] = e.code
      redirecgt_to :controller => 'plugin'
    end
    oauth_user = JSON.parse(token.get('https://api.github.com/user').body)
    user = User.first(:conditions => {:github_name => oauth_user['login']})
    user ||= User.new
    user.github_name = oauth_user['login']
    user.name = oauth_user['name']
    user.icon_url = oauth_user['avatar_url']
    user.save
    
    session[:current_user] = user
    session.delete :oauth_referer

    referer = session[:oauth_referer]
    session.delete :oauth_referer
    referer = url_for(:controller => 'plugins')
    redirect_to referer
  end

  def logout
    session.delete :current_user
    redirect_to :controller => 'plugins'
  end

  private
  def client
    OAuth2::Client.new(
      Setting[:oauth_request_client_id],
      Setting[:oauth_request_client_secret],
      :site => 'https://github.com',
      :authorize_url => '/login/oauth/authorize',
      :token_url => '/login/oauth/access_token'
      )
  end
end

app/controllers/plugins_controller.rb
class PluginsController < ApplicationController
  include PluginsHelper

  # GET /plugins
  # GET /plugins.json
  def index
    @keywords = params[:q] || ''
    search = Plugin.search_by_keywords(@keywords)
    @plugins = search.order('updated_at DESC').page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @plugins }
    end
  end

  # GET /plugins/1
  # GET /plugins/1.json
  def show
    @plugin = Plugin.find(params[:id])

    if params[:format] == 'json'
      @plugin.downloads ||= 0
      @plugin.downloads += 1
      Plugin.record_timestamps = false
      @plugin.save
      Plugin.record_timestamps = true
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @plugin }
    end
  end

  # GET /plugins/new
  # GET /plugins/new.json
  def new
    @plugin = Plugin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @plugin }
    end
  end

  # GET /plugins/1/edit
  def edit
    @plugin = Plugin.find(params[:id])
  end

  # POST /plugins
  # POST /plugins.json
  def create
    unless login?
      raise 'not allowed not-login users to create new plugins'
    end
    @plugin = Plugin.new(params[:plugin])
    @plugin.create_user = current_user
    @plugin.update_user = current_user
    respond_to do |format|
      if @plugin.save
        format.html { redirect_to @plugin, :notice => 'Plugin was successfully created.' }
        format.json { render :json => @plugin, :status => :created, :location => @plugin }
      else
        format.html { render :action => "new" }
        format.json { render :json => @plugin.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /plugins/1
  # PUT /plugins/1.json
  def update
    unless login?
      raise 'not allowed not-login users to update  plugins'
    end
    @plugin = Plugin.find(params[:id])
    @plugin.update_user = current_user
    respond_to do |format|
      if @plugin.update_attributes(params[:plugin])
        format.html { redirect_to @plugin, :notice => 'Plugin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @plugin.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /plugins/1
  # DELETE /plugins/1.json
  def destroy
    unless login?
      raise 'not allowed not-login users to delete plugins'
    end
    @plugin = Plugin.find(params[:id])
    @plugin.destroy

    respond_to do |format|
      format.html { redirect_to plugins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login?
    not session[:current_user].nil?
  end
  def current_user
    session[:current_user]
  end
end

app/helpers/plugins_helper.rb
module PluginsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def link_to_github(user)
    html = image_tag(user.icon_url, :width => '16px')
    html << link_to(user.name, "https://github.com/#{user.github_name}")
    html
  end
end

app/views/layouts/application.html.haml
!!!
%html
 %head
  %meta{'http-equiv'=>'content', :content=>'text/thml; charset=utf-8'}
  = stylesheet_link_tag 'application'
  = javascript_include_tag 'application'
  = favicon_link_tag 'favicon.ico'
  = csrf_meta_tags
  %title Redbrew | A missing plugin manager for Redmine
 %body
  #wrap
   #header
    #title
     = link_to image_tag("logo.png", :title => "Redbrew"), root_path
    #account
     - if login?
      = link_to_github current_user
      = link_to('Logout', {:controller => 'login', :action => 'logout'}, { :class => 'button small green'})
     - else
      = link_to('Login with Github account', {:controller => 'login', :action => 'oauth'}, {:class => 'button small green'})

   #content
    = yield

  .footer
   Copyright (C) 2012-
   = link_to 'codefirst.org', 'http://www.codefirst.org'
   All rights reserved.

app/views/plugins/_form.html.haml
= form_for @plugin do |f|
  -if @plugin.errors.any?
    .notice.error
      = "#{pluralize(@plugin.errors.count, "error")} prohibited this plugin from being saved:"
      %ul{:style => 'margin-bottom:0'}
        - @plugin.errors.full_messages.each do |msg|
          %li= msg

  %table
    %tr
      %td.label= f.label :name
      %td= f.text_field :name, {:size => 40}
    %tr
      %td.label= f.label :url
      %td= f.text_field :url, {:size => 100}
    %tr
      %td.label= f.label :description
      %td= f.text_field :description, {:size => 100}
    %tr
      %td.label= f.label :formula
      %td= f.text_area :formula
    %tr
      %td.label{:style => 'border:none;'} &nbsp;
      %td{:style => 'border:none;'}= f.submit 'Save'

app/views/plugins/_searchbox.html.haml
#search-box
  = form_tag({:action => 'index'}, {:method => 'get'}) do
    = text_field_tag :q, keywords, {:placeholder => 'Search word', :autofocus => true}
    %button.small.blue Search

app/views/plugins/edit.html.haml
%h4 Editing plugin

= render 'form'

.left-buttons
  = link_to 'Show', @plugin
  \|
  = link_to 'Back', plugins_path
.right-buttons
  = link_to 'Remove', @plugin, :confirm => 'Are you sure?', :method => :delete

:javascript
  var editor = CodeMirror.fromTextArea(document.getElementById("plugin_formula"), {
    mode: "text/x-ruby",
    tabMode: "indent",
    matchBrackets: true,
    indentUnit: 4,
    lineNumbers: true
  });

app/views/plugins/index.html.haml
= render 'plugins/searchbox', :keywords => @keywords

- if login?
  .right
    = link_to('New Plugin', new_plugin_path, {:class =>'button blue small' })

%table
  %tr
    %th Name
    %th Updated
    %th Description

  - @plugins.each do |plugin|
    %tr
      %td= link_to plugin.name, :action => 'show', :id => plugin
      %td= distance_of_time_in_words_to_now(plugin.updated_at) + ' ago'
      %td= plugin.description
.center
  = paginate @plugins

app/views/plugins/new.html.haml
%h4 New plugin

= render 'form'

= link_to 'Back', plugins_path

:javascript
  var editor = CodeMirror.fromTextArea(document.getElementById("plugin_formula"), {
    mode: "text/x-ruby",
    tabMode: "indent",
    matchBrackets: true,
    indentUnit: 4,
    lineNumbers: true
  });

app/views/plugins/show.html.haml
- if notice
  %p.notice.success= notice

%table
  %tr
    %td.label Name:
    %td= @plugin.name
  %tr
    %td.label Downloads:
    %td= @plugin.downloads || 0
  %tr
    %td.label Url:
    %td= link_to @plugin.url, @plugin.url
  %tr
    %td.label Description:
    %td= @plugin.description
  %tr
    %td.label Formula:
    %td= text_area_tag 'plugin_formula', @plugin.formula
  %tr
    %td.label Created:
    %td
      - unless @plugin.create_user.nil?
        = link_to_github @plugin.create_user
  %tr
    %td.label Updated:
    %td
      - unless @plugin.update_user.nil?
        = link_to_github @plugin.update_user

.left-buttons
  - if login?
    = link_to 'Edit', edit_plugin_path(@plugin)
    \|
    = link_to 'Back', plugins_path
  - else
    = link_to 'Back', plugins_path

- if login?
  .right-buttons
    = link_to 'Remove', @plugin, :confirm => 'Are you sure?', :method => :delete

:javascript
  var editor = CodeMirror.fromTextArea(document.getElementById("plugin_formula"), {
    mode: "text/x-ruby",
    tabMode: "indent",
    matchBrackets: true,
    indentUnit: 4,
    lineNumbers: true,
    readOnly : true
  });

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Github name
    %th Icon
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.github_name
      %td
        %img{:src => user.icon_url}
      %td
        %ul.button-bar
          %li.first.last
            = link_to 'Detail', user

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Github name:
  = @user.github_name
%p
  %b Icon:
  %img{:src => @user.icon_url}

= link_to 'Back', users_path